apiVersion: apps/v1 # k8s versions 1.8
kind: StatefulSet # Stateful set is used in conjuction with the headless yaml in order to maintain persistence of the pods 
metadata:
  name: mongodep
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.0 # mongo version 4.0 is being used as the shared image
        command:
        - mongod
        - "--bind_ip_all" # binds mongod instance to all IPv4 addresses
        - "--replSet" # specifying replica set name as rs0
        - rs0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume # mongod db's stored under /media/db
          mountPath: /media/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume # mounted volumes are set to read/write with a max cap of 1 GB
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
